spring:
  application:
    name: SLOG

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  # MySQL
  # datasource:
  #   url: jdbc:mysql://localhost:3306/slog?useSSL=false&serverTimezone=UTC
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      name: nnnn
      password: "9999"
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: sa@gmail.com

jwt:
  header: Authorization
  issuer: "sa@gmail.com"
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

server:
  port: 8080
